client.println("HTTP/1.1 200 OK");
client.println("Content-Type: text/html");
client.println();
client.println("<!DOCTYPE html>");
client.println("<html lang=\\" ru\\" style=\\" height : 100 % ;\\">");
client.println("<head>");
client.println("    <!-- Базовые HTML настройки -->");
client.println("    <meta charset=\\" UTF - 8\\">");
client.println("    <meta name=\\" viewport\\" content=\\" width = device - width, initial - scale = 1.0\\">");
client.println("    <title>Disater Box Help Website</title>");
client.println("    <style>");
client.println("        :root{");
client.println("            --textColor: #000000;");
client.println("            --have: #ff0000;");
client.println("            --havent: #008000;");
client.println("        }");
client.println("        *{");
client.println("            margin: 0;");
client.println("            padding: 0;");
client.println("            box-sizing: border-box;");
client.println("            list-style: none;");
client.println("        }");
client.println("        html,");
client.println("        body{");
client.println("            height: 100%;");
client.println("        }");
client.println("        body{");
client.println("            background: white;");
client.println("            display: flex;");
client.println("            justify-content: space-evenly;");
client.println("        }");
client.println("        @media screen and (min-width:768px) {");
client.println("            body .menu > .showing button{");
client.println("                font-size: 30px;");
client.println("                width: 200px;");
client.println("                overflow: hidden;");
client.println("            }");
client.println("            .settings{");
client.println("                height: 50px;");
client.println("            }");
client.println("            .settings > a{");
client.println("                font-size: 20px;");
client.println("            }");
client.println("            .menu > .showing span{");
client.println("                font-size: 25px;");
client.println("            }");
client.println("            .leftMain > .showing > li > span, .rightMain > .showingimgs > ul > li > span{");
client.println("                font-size: 24px;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (min-width: 320px){");
client.println("            body .showingimgs li {");
client.println("                border-right: 2px solid gray;");
client.println("            }");
client.println("            body .showing span{");
client.println("                font-size: 100%;");
client.println("            }");
client.println("            body .showing > li{");
client.println("                flex-wrap: wrap;");
client.println("                width: 100%;");
client.println("            }");
client.println("            .showingimgs li > .img > img{");
client.println("                height: 25%;");
client.println("                width: 50%;");
client.println("            }");
client.println("            .showingimgs li > span{");
client.println("                width: 100%;");
client.println("                display: flex;");
client.println("                flex-wrap: wrap;");
client.println("                height: 12%;");
client.println("            }");
client.println("            body .showingimgs li:nth-child(1) > span > span{");
client.println("                text-align: center;");
client.println("                height: 50%;");
client.println("                overflow-wrap: anywhere;");
client.println("                white-space: normal;");
client.println("            }");
client.println("            body .value{");
client.println("                display: flex;");
client.println("                justify-content: center;");
client.println("                align-items: center;");
client.println("                font-size: 20px;");
client.println("            }");
client.println("            body .settings{");
client.println("                width: 100%;");
client.println("            }");
client.println("            .back{");
client.println("                width: 100px;");
client.println("            }");
client.println("            .menu > .showing button{");
client.println("                width: 40px;");
client.println("                overflow: hidden;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (min-width: 1024px){");
client.println("            .showingimgs li > .img > img{");
client.println("                width: 20%;");
client.println("                height: 40%;");
client.println("            }");
client.println("            .showing span{");
client.println("                font-size: 200%;");
client.println("            }");
client.println("            .showingimgs span{");
client.println("                font-size: 100%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (min-width:1440px) {");
client.println("            body .showing span{");
client.println("                font-size: 240%;");
client.println("            }");
client.println("            body .showingimgs span{");
client.println("                font-size: 120%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (min-width:769px) {");
client.println("            body .showingimgs > ul > li > .img > img{");
client.println("                width: 50%;");
client.println("                height: 50%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (max-width:425px) {");
client.println("            body .up{");
client.println("                border-bottom: 2px solid gray;");
client.println("            }");
client.println("            body .showingimgs > ul > li{");
client.println("                border-right: 2px solid gray;");
client.println("            }");
client.println("            body > .rightMain{");
client.println("                padding: 0;");
client.println("            }");
client.println("            body .date{");
client.println("                margin-bottom: 10px;");
client.println("            }");
client.println("            .menu > button{");
client.println("                width: 100px;");
client.println("            }");
client.println("            body > .leftMain > .showing > li > span{");
client.println("                font-size: 22.5px;");
client.println("            }");
client.println("            .showingimgs li > .img > img{");
client.println("                height: 25%;");
client.println("                width: 100%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (max-width:768px) {");
client.println("            .leftMain > .showing > li > span, .rightMain > .showingimgs > ul > li > span{");
client.println("                font-size: 22px;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (width:768px) {");
client.println("            .showingimgs li > .img > img{");
client.println("                height: 40%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (width:425px) {");
client.println("            body .showingimgs > ul > li > .img > img{");
client.println("                width: 50%;");
client.println("                height: 50%;");
client.println("            }");
client.println("        }");
client.println("        .showingimgs > ul > li > .titttle{");
client.println("            overflow-wrap: anywhere;");
client.println("            white-space: normal;");
client.println("            text-align: center;");
client.println("        }");
client.println("        .leftMain{");
client.println("            padding: 10px;");
client.println("            display: flex;");
client.println("            flex-direction: column;");
client.println("            width: 30%;");
client.println("            height: 100%;");
client.println("            border-right: 2px solid gray;");
client.println("        }");
client.println("        .rightMain{");
client.println("            width: 70%;");
client.println("            height: 100%;");
client.println("            padding: 10px;");
client.println("        }");
client.println("            .logo { margin-bottom: 10px; }");
client.println("            .date { margin-bottom: 50px; }");
client.println("            .showing { height: 75%; display: flex; flex-direction: column; justify-content: space-between; flex-wrap: nowrap; }");
client.println("            .showingimgs > ul > li > .titttle { text-align: center; }");
client.println("            .showing > li { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid gray; }");
client.println("            .showing span { font-size: 100%; }");
client.println("            .showing .pokasanie { text-align: center; }");
client.println("            .settings { width: 50%; position: static; }");
client.println("            .showing { margin-bottom: 30px; }");
client.println("            .showingimgs { width: 100%; height: 100%; display: flex; flex-direction: column; justify-content: space-evenly; border: 1px solid gray; }");
client.println("            .up, .bottom { width: 100%; height: 49%; display: flex; justify-content: space-evenly; }");
client.println("            .up { border-bottom: 5px solid gray; }");
client.println("            .showingimgs li { height: 100%; width: 30%; display: flex; flex-direction: column; justify-content: space-between; align-items: center; border-right: 5px solid gray; }");
client.println("            .showingimgs > .up > li:nth-child(3), .showingimgs > .bottom > li:nth-child(3) { border-right: none; }");
client.println("            .showingimgs .img { width: 100%; height: 75%; display: flex; flex-direction: column; justify-content: space-evenly; align-items: center; }");
client.println("            .img > img { width: 10%; height: 70%; }");
client.println("            .values { width: 100%; height: 25%; }");
client.println("            .showingimgs > .bottom > li:nth-child(1) > .img { height: 66%; }");
client.println("            .value { text-align: center; width: 100%; height: 50%; }");
client.println("            .have { text-align: center; width: 100%; height: 50%; background: var(--havent); border: 2px solid black; }");
client.println("            body .value_tem { border: 2px solid black; border-bottom: none; }");
client.println("            body .value_hum { border: 2px solid black; }");
client.println("            body .have_flame { height: 100%; }");
client.println("            body .have_rain, .have_wibro, .have_wind { border-bottom: none; }");
client.println("            body .value_rain, .value_wibro, .value_wind { border: 2px solid black; }");
client.println("            body .have_gas { height: 100%; }");
client.println("            .menu { display: none; position: absolute; z-index: 52; height: 90%; width: 90%; top: 5%; left: 5%; border: 2px solid black; background: white; }");
client.println("            .bloored { filter: blur(100%); }");
client.println("            .back { width: 15%; height: 5%; }");
client.println("            .on, .off { width: 100px; height: 100%; }");
client.println("            .tittle { width: 150px; }");
client.println("        </style>");
client.println("    </head>");
client.println("    <body>");
client.println("        <div class=\"menu\">");
client.println("            <button class=\"back\"><a href=\"#\">Назад</a></button>");
client.println("            <ul class=\"showing\">");
client.println("                <li><span class=\"tittle\">Датчик осадков</span> <span class=\"pokasanie firstt\">Выкл</span> <button class=\"on\">Включить</button> <button class=\"off\">Выключить</button></li>");
client.println("                <li><span class=\"tittle\">Датчик температуры</span> <span class=\"pokasanie secondd\">Выкл</span><button class=\"on\">Включить</button> <button class=\"off\">Выключить</button></li>");
client.println("                <li><span class=\"tittle\">Датчик ветра</span> <span class=\"pokasanie thirdd\">Выкл</span><button class=\"on\">Включить</button> <button class=\"off\">Выключить</button></li>");
client.println("                <li><span class=\"tittle\">Датчик газа</span> <span class=\"pokasanie fourthh\">Выкл</span><button class=\"on\">Включить</button> <button class=\"off\">Выключить</button></li>");
client.println("                <li><span class=\"tittle\">Датчик влажности</span> <span class=\"pokasanie fifthh\">Выкл</span><button class=\"on\">Включить</button> <button class=\"off\">Выключить</button></li>");
client.println("                <li><span class=\"tittle\">Датчик вибрации</span> <span class=\"pokasanie sixthh\">Выкл</span><button class=\"on\">Включить</button> <button class=\"off\">Выключить</button></li>");
client.println("        </ul>");
client.println("    </div>");
client.println("    <div class=\"leftMain bloored\">");
client.println("        <div class=\"logo\">");
client.println("            <span class=\"title\">DisasterBOX</span>");
client.println("        </div>");
client.println("        <span class=\"date\"></span>");
client.println("        <ul class=\"showing\">");
client.println("            <li><span class=\"tittle\">Осадки</span> <span class=\"pokasanie first\">0 мм</span></li>");
client.println("            <li><span class=\"tittle\">Температура</span> <span class=\"pokasanie second\">0</span></li>");
client.println("            <li><span class=\"tittle\">Ветер</span> <span class=\"pokasanie third\">0 м/с</span></li>");
client.println("            <li><span class=\"tittle\">Крит. доза газов</span> <span class=\"pokasanie fourth\">Нет</span></li>");
client.println("            <li><span class=\"tittle\">Влажность</span> <span class=\"pokasanie fifth\">70%</span></li>");
client.println("            <li><span class=\"tittle\">Подземные толчки</span> <span class=\"pokasanie sixth\">1 балл</span></li>");
client.println("            <li><span class=\"tittle\">Огонь</span> <span class=\"pokasanie seventh\">Есть</span></li>");
client.println("        </ul>");
client.println("        <button class=\"settings\"><a href=\"#\">Настройка датчиков</a></button>");
client.println("    </div>");
client.println("    <div class=\"rightMain\">");
client.println("        <div class=\"showingimgs\">");
client.println("            <ul class=\"up\">");
client.println("                <li>");
client.println("                    <span class=\"titttle needfix\"><span>Темп. ,</span><span>влажн.</span></span>");
client.println("                    <div class=\"img\">");
client.println("                        <img src=\"tem.png\" alt=\"\">");
client.println("                    </div>");
client.println("                    <div class=\"values\">");
client.println("                        <div class=\"value value_tem\"><span>0</span></div>");
client.println("                        <div class=\"value value_hum\"><span>75%</span></div>");
client.println("                    </div>");
client.println("                </li>");
client.println("                <li>");
client.println("                    <span class=\"titttle\">Осадки</span>");
client.println("                    <div class=\"img\">");
client.println("                        <img src=\"rain.jfif\" alt=\"\">");
client.println("                    </div>");
client.println("                    <div class=\"values\">");
client.println("                        <div class=\"have have_rain\"></div>");
client.println("                        <div class=\"value value_rain\"><span>0 мм</span></div>");
client.println("                    </div>");
client.println("                </li>");
client.println("                <li>");
client.println("                    <span class=\"titttle\">Подземные толчки</span>");
client.println("                    <div class=\"img\">");
client.println("                        <img src=\"zem.png\" alt=\"\">");
client.println("                    </div>");
client.println("                    <div class=\"values\">");
client.println("                        <div class=\"have have_wibro\"></div>");
client.println("                        <div class=\"value value_wibro\"><span>1 б.</span></div>");
client.println("                    </div>");
client.println("                </li>");
client.println("            </ul>");
client.println("            <ul class=\"bottom\">");
client.println("                <li>");
client.println("                    <span class=\"titttle\">Огонь</span>");
client.println("                    <div class=\"img\">");
client.println("                        <img src=\"flame.jfif\" alt=\"\">");
client.println("                    </div>");
client.println("                    <div class=\"values\">");
client.println("                        <div class=\"have have_flame\"></div>");
client.println("                    </div>");
client.println("                </li>");
client.println("                <li>");
client.println("                    <span class=\"titttle\">Газ</span>");
client.println("                    <div class=\"img\">");
client.println("                        <img src=\"gas.png\" alt=\"\">");
client.println("                    </div>");
client.println("                    <div class=\"values\">");
client.println("                <div class=\"value value_gas\"></div>");
client.println("            </div>");
client.println("            </li>");
client.println("            <li>");
client.println("            <span class=\"titttle\">Скорость ветра</span>");
client.println("            <div class=\"img\">");
client.println("                <img src=\"wind.jfif\" alt=\"\">");
client.println("            </div>");
client.println("            <div class=\"values\">");
client.println("                <div class=\"have have_wind\"></div>");
client.println("                <div class=\"value value_wind\"><span>0 м/с</span></div>");
client.println("            </div>");
client.println("            </li>");
client.println("        </ul>");
client.println("        </div>");
client.println("        <script>");
client.println("            let date = document.querySelector('.date')");
client.println("            setInterval(() => {");
client.println("                date.innerHTML = `${(new Date).getDay()}.${(new Date).getMonth()}.${(new Date).getFullYear()} ${(new Date).getHours()}:${(new Date).getMinutes()}:${(new Date).getSeconds()}`");
client.println("            },1000)");
client.println("            let value_hum = document.querySelector('.value_hum')");
client.println("            let value_tem = document.querySelector('.value_tem')");
client.println("            let value_rain = document.querySelector('.value_rain')");
client.println("            let have_rain = document.querySelector('.have_rain')");
client.println("            let value_wibro = document.querySelector('.value_wibro')");
client.println("            let have_wibro = document.querySelector('.have_wibro')");
client.println("            let have_flame = document.querySelector('.have_flame')");
client.println("            let have_gas = document.querySelector('.have_flame')");
client.println("            let value_wind = document.querySelector('.value_wibro')");
client.println("            let have_wind = document.querySelector('.have_wibro')");
client.println("            let firstv = document.querySelector('.first')");
client.println("            let secondv = document.querySelector('.second')");
client.println("            let thirdv = document.querySelector('.third')");
client.println("            let fourthv = document.querySelector('.fourth')");
client.println("            let fifthv = document.querySelector('.fifth')");
client.println("            let sixthv = document.querySelector('.sixth')");
client.println("            let seventhv = document.querySelector('.seventh')");
client.println("            value_hum.innerHTML = fifthv.innerHTML");
client.println("            value_tem.innerHTML = secondv.innerHTML");
client.println("            value_rain.innerHTML = firstv.innerHTML");
client.println("            value_wibro.innerHTML = sixthv.innerHTML");
client.println("            value_wind.innerHTML = thirdv.innerHTML");
client.println("            if (seventhv.innerText == 'Есть') have_flame.style.background = 'var(--have)'");
client.println("            else if (!seventhv.innerText == 'Есть') have_flame.style.background = 'var(--havent)'");
client.println("            if (fourthv.innerText == 'Есть') have_gas.style.background = 'var(--have)'");
client.println("            else if (!fourthv.innerText == 'Есть') have_flame.style.background = 'var(--havent)'");
client.println("            let set = document.querySelector('.settings')");
client.println("            let menu = document.querySelector('.menu')");
client.println("            set.addEventListener('click', () => {");
client.println("                menu.style.display = 'block'");
client.println("                menu.querySelectorAll('.on').forEach(el => {");
client.println("                    el.addEventListener('click', () => {");
client.println("                        el.parentNode.querySelector('.pokasanie').innerHTML = 'Вкл'");
client.println("                    })");
client.println("                })");
client.println("                menu.querySelectorAll('.off').forEach(el => {");
client.println("                    el.addEventListener('click', () => {");
client.println("                        el.parentNode.querySelector('.pokasanie').innerHTML = 'Выкл'");
client.println("                    })");
client.println("                })");
client.println("                document.querySelector('.back').addEventListener('click', () => {");
client.println("                    menu.style.display = 'none'");
client.println("                })");
client.println("            })");
client.println("            if (window.innerWidth <= 425){");
client.println("                document.querySelectorAll('.on').forEach(el => el.innerHTML = 'Вкл')");
client.println("                document.querySelectorAll('.off').forEach(el => el.innerHTML = 'Выкл')");
client.println("                document.querySelector('.needfix').innerHTML = 'Темп., влаж.'");
client.println("                secondv.parentNode.querySelector('.tittle').innerHTML = 'Темп.'");
client.println("                fifthv.parentNode.querySelector('.tittle').innerHTML = 'Влажн.'");
client.println("                sixthv.parentNode.querySelector('.tittle').innerHTML = 'Толчки'");
client.println("            }");
client.println("            window.addEventListener('resize', () => {");
client.println("                if (window.innerWidth <= 425){");
client.println("                    document.querySelectorAll('.on').forEach(el => el.innerHTML = 'Вкл')");
client.println("                    document.querySelectorAll('.off').forEach(el => el.innerHTML = 'Выкл')");
client.println("                    document.querySelector('.needfix').innerHTML = 'Темп., влаж.'");
client.println("                    secondv.parentNode.querySelector('.tittle').innerHTML = 'Темп.'");
client.println("                    fifthv.parentNode.querySelector('.tittle').innerHTML = 'Влажн.'");
client.println("                    sixthv.parentNode.querySelector('.tittle').innerHTML = 'Толчки'");
client.println("                }");
client.println("            })");
client.println("        </script>");
client.println("    </body>");
client.println("</html>");