client.println("<!DOCTYPE html>");
client.println("<html lang='ru' style='height: 100%;'>");
client.println("<head>");
client.println("    <!-- Базовые HTML настройки -->");
client.println("    <meta charset='UTF-8'>");
client.println("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
client.println("    <title>Disater Box Help Website</title>");
client.println("<script>");
client.println("function readSensorFlame() {");
client.println("  nocache = "&nocache="                                                    + Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("document.getElementById("switch_flame_1").innerHTML = this.responseText;");
client.println("document.getElementById("switch_flame_2").innerHTML = this.responseText;");
client.println("}}}}");
client.println("  request.open("GET", "ajax_flame" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function readSensorLight() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("document.getElementById("switch_light").innerHTML = this.responseText;");
client.println("}}}}");
client.println("  request.open("GET", "ajax_light" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function readSensorWater() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("document.getElementById("switch_water_1").innerHTML = this.responseText;");
client.println("document.getElementById("switch_water_2").innerHTML = this.responseText;");
client.println("}}}}");
client.println("  request.open("GET", "ajax_water" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function readSensorVibr() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("document.getElementById("switch_vibr_1").innerHTML = this.responseText;");
client.println("document.getElementById("switch_vibr_2").innerHTML = this.responseText;");
client.println("}}}}");
client.println("  request.open("GET", "ajax_vibr" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function readSensorPrs() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("document.getElementById("switch_prs_1").innerHTML = this.responseText;");
client.println("document.getElementById("switch_prs_2").innerHTML = this.responseText;");
client.println("}}}}");
client.println("  request.open("GET", "ajax_prs" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function readSensorDHTtem() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("document.getElementById("switch_DHTtem_1").innerHTML = this.responseText;");
client.println("document.getElementById("switch_DHTtem_2").innerHTML = this.responseText;");
client.println("}}}}");
client.println("  request.open("GET", "ajax_DHTtem" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function readSensorDHThum() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("document.getElementById("switch_DHThum_1").innerHTML = this.responseText;");
client.println("document.getElementById("switch_DHThum_2").innerHTML = this.responseText;");
client.println("}}}}");
client.println("  request.open("GET", "ajax_DHThum" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function readSensorMQ2() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("document.getElementById("switch_MQ2_1").innerHTML = this.responseText;");
client.println("document.getElementById("switch_MQ2_2").innerHTML = this.responseText;");
client.println("}}}}");
client.println("  request.open("GET", "ajax_MQ2" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function addFlag1() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("}}}}");
client.println("  request.open("GET", "ajax_FL1" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("function addFlag2() {");
client.println("  nocache = "&nocache="+ Math.random() * 1000000;");
client.println("  var request = new XMLHttpRequest();");
client.println("  request.onreadystatechange = function() {");
client.println("if (this.readyState == 4) {");
client.println("if (this.status == 200) {");
client.println("if (this.responseText != null) {");
client.println("}}}}");
client.println("  request.open("GET", "ajax_FL2" + nocache, true);");
client.println("  request.send(null);");
client.println("}");
client.println("</script>");
client.println("    <style>");
client.println("        :root{");
client.println("            --textColor: #000000;");
client.println("            --have: #ff0000;");
client.println("            --havent: #008000;");
client.println("        }");
client.println("        *{");
client.println("            margin: 0;");
client.println("            padding: 0;");
client.println("            box-sizing: border-box;");
client.println("            list-style: none;");
client.println("        }");
client.println("        html,");
client.println("        body{");
client.println("            height: 100%;");
client.println("        }");
client.println("        body{");
client.println("            background: white;");
client.println("            display: flex;");
client.println("            justify-content: space-evenly;");
client.println("        }");
client.println("        @media screen and (min-width:768px) {");
client.println("            body .menu > .showing button{");
client.println("                font-size: 30px;");
client.println("                width: 200px;");
client.println("                overflow: hidden;");
client.println("            }");
client.println("            .settings{");
client.println("                height: 50px;");
client.println("            }");
client.println("            .settings{");
client.println("                font-size: 20px;");
client.println("            }");
client.println("            .menu > .showing span{");
client.println("                font-size: 25px;");
client.println("            }");
client.println("            .leftMain > .showing > li > span, .rightMain > .showingimgs > ul > li > span{");
client.println("                font-size: 24px;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (min-width: 320px){");
client.println("            body .showing span{");
client.println("                font-size: 100%;");
client.println("            }");
client.println("            body .showing > li{");
client.println("                flex-wrap: wrap;");
client.println("                width: 100%;");
client.println("            }");
client.println("            .showingimgs li > .img > img{");
client.println("                height: 25%;");
client.println("                width: 50%;");
client.println("            }");
client.println("            body .value{");
client.println("                display: flex;");
client.println("                justify-content: center;");
client.println("                align-items: center;");
client.println("                font-size: 20px;");
client.println("            }");
client.println("            body .settings{");
client.println("                width: 100%;");
client.println("            }");
client.println("            .back{");
client.println("                width: 100px;");
client.println("            }");
client.println("            .menu > .showing button{");
client.println("                height: 45px;");
client.println("                width: 40px;");
client.println("                overflow: hidden;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (min-width: 1024px){");
client.println("            .showingimgs li > .img > img{");
client.println("                width: 20%;");
client.println("                height: 40%;");
client.println("            }");
client.println("            .showing span{");
client.println("                font-size: 200%;");
client.println("            }");
client.println("            .showingimgs span{");
client.println("                font-size: 100%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (min-width:1440px) {");
client.println("            body .showing span{");
client.println("                font-size: 240%;");
client.println("            }");
client.println("            body .showingimgs span{");
client.println("                font-size: 120%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (min-width:769px) {");
client.println("            body .showingimgs > ul > li > .img > img{");
client.println("                width: 50%;");
client.println("                height: 50%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (max-width:425px) {");
client.println("            body > .rightMain{");
client.println("                padding: 0;");
client.println("            }");
client.println("            body .date{");
client.println("                margin-bottom: 10px;");
client.println("            }");
client.println("            .menu > button{");
client.println("                width: 100px;");
client.println("            }");
client.println("            body > .leftMain > .showing > li > span{");
client.println("                font-size: 22.5px;");
client.println("            }");
client.println("            .showingimgs li > .img > img{");
client.println("                height: 25%;");
client.println("                width: 100%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (max-width:768px) {");
client.println("            .leftMain > .showing > li > span, .rightMain > .showingimgs > ul > li > span{");
client.println("                font-size: 22px;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (width:768px) {");
client.println("            .showingimgs li > .img > img{");
client.println("                height: 40%;");
client.println("            }");
client.println("        }");
client.println("        @media screen and (width:425px) {");
client.println("            body .showingimgs > ul > li > .img > img{");
client.println("                width: 50%;");
client.println("                height: 50%;");
client.println("            }");
client.println("        }");
client.println("        ");
client.println("        .leftMain{");
client.println("            padding: 40px;");
client.println("            margin-top: 40px;");
client.println("            margin-bottom: 20px;");
client.println("            margin-left: 40px;");
client.println("            display: flex;");
client.println("            flex-direction: column;");
client.println("            width: 30%;");
client.println("            height: calc(100% - 80px);");
client.println("            background-color: #e5e2e2;");
client.println("            border-radius: 20px;");
client.println("        }");
client.println("        .rightMain{");
client.println("            width: 70%;");
client.println("            height: 100%;");
client.println("            padding: 20px;");
client.println("        }");
client.println("            .logo { margin-bottom: 10px; }");
client.println("            .date { margin-bottom: 10px; }");
client.println("            .vibor { margin-bottom: 40px; }");
client.println("            .titttle { text-align: center;}");
client.println("            .showing { height: 75%; display: flex; flex-direction: column; justify-content: space-between; flex-wrap: nowrap; }");
client.println("            .showing > li { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid gray; }");
client.println("            .showing span { font-size: 100%; }");
client.println("            .showing .pokasanie { text-align: center; }");
client.println("            .settings { width: 50%; position: static; color: rgb(142, 142, 255); border-radius: 10px;}");
client.println("            .showing { margin-bottom: 30px; }");
client.println("            .showingimgs { width: 100%; height: 100%; display: flex; flex-direction: column; justify-content: space-evenly; }");
client.println("            .up, .bottom { width: 100%; height: 49%; display: flex; justify-content: space-evenly; padding-bottom: 10px; padding-top: 10px;}");
client.println("            .up { padding-top: 15px;}");
client.println("            .bottom { padding-bottom: 15px;}");
client.println("            .showingimgs li { height: 100%; width: 30%; padding:2%;display: flex; flex-direction: column; justify-content: space-between; align-items: center; background-color: #e5e2e2;  box-sizing: border-box; border-radius: 20px;}");
client.println("            .showingimgs .img { width: 100%; height: 75%; display: flex; flex-direction: column; justify-content: space-evenly; align-items: center; }");
client.println("            .img > img { width: 10%; height: 70%; }");
client.println(".img>p {font-size: 100px;}");
client.println("            .values { width: 100%; height: 25%; }");
client.println("            .selectDB { color: rgb(142, 142, 255); }");
client.println("            .showingimgs > .bottom > li:nth-child(1) > .img { height: 66%; }");
client.println("            .value { text-align: center; width: 100%; height: 50%; }");
client.println("            .have { text-align: center; width: 100%; height: 50%; background: var(--havent);}");
client.println("            body .value_tem { border: 2px solid black; border-bottom: none; }");
client.println("            body .value_hum { border: 2px solid black; }");
client.println("            body .have_flame { height: 50%; }");
client.println("            body .have_rain, .have_wibro, .have_wind { border-bottom: none; }");
client.println("            body .value_rain,.value_gass,.value_flame,.have_gas, .value_wibro, .value_wind { border: 2px solid black; }");
client.println("            body .have_gas { height: 50%; border-bottom: none;}");
client.println("            .menu { display: none; position: absolute; z-index: 52; height: auto; width: 90%; top: 50%; left: 50%;  transform: translateX(-50%) translateY(-50%); background: white;border-radius: 10px; box-shadow: 0 0 5px 1px black;}");
client.println("            .bloored { filter: blur(100%); }");
client.println("            .back { width: 140px; height: 40px; font-size: 20px; color: rgb(142, 142, 255); margin-left: 30px; margin-top: 10px;}");
client.println("            .on, .off { width: 100px; height: 100%; }");
client.println("            .tittle { width: 150px; }");
client.println("            .SHOW{padding: 30px; height:87%; margin-bottom: 0; gap: 5px;}");
client.println("            .SHOW>li{border-bottom: none; background-color: #e5e2e2; padding: 10px;}");
client.println("            .hj {width: 260px;}");
client.println("            button{ border-radius: 5px;}");
client.println("        </style>");
client.println("    </head>");
client.println("    <body>");
client.println("        <div class='menu'>");
client.println("            <button class='back'>Назад</button>");
client.println("            <ul class='showing SHOW'>");
client.println("                <li><span class='tittle hj'>Датчик осадков</span> <span class='pokasanie firstt'>Выкл</span> <button class='on'>Включить</button> <button class='off'>Выключить</button></li>");
client.println("                <li><span class='tittle hj'>Датчик освещёности</span> <span class='pokasanie ninthh'>Выкл</span> <button class='on'>Включить</button> <button class='off'>Выключить</button></li>");
client.println("                <li><span class='tittle hj'>Датчик газа</span> <span class='pokasanie fourthh'>Выкл</span><button class='on'>Включить</button> <button class='off'>Выключить</button></li>");
client.println("                <li><span class='tittle hj'>Датчик влажности</span> <span class='pokasanie fifthh'>Выкл</span><button class='on'>Включить</button> <button class='off'>Выключить</button></li>");
client.println("                <li><span class='tittle hj'>Датчик температуры</span> <span class='pokasanie secondd'>Выкл</span><button class='on'>Включить</button> <button class='off'>Выключить</button></li>");
client.println("                <li><span class='tittle hj'>Датчик вибрации</span> <span class='pokasanie sixthh'>Выкл</span><button class='on'>Включить</button> <button class='off'>Выключить</button></li>");
client.println("                <li><span class='tittle hj'>Датчик огня</span> <span class='pokasanie seventhh'>Выкл</span><button class='on'>Включить</button> <button class='off'>Выключить</button></li>");
client.println("                <li><span class='tittle hj'>Датчик давления</span> <span class='pokasanie eighteenthh'>Выкл</span><button class='on'>Включить</button> <button class='off'>Выключить</button></li>");
client.println("        </ul>");
client.println("    </div>");
client.println("    <div class='leftMain bloored'>");
client.println("        <div class='logo'>");
client.println("            <span class='title'>DisasterBOX</span>");
client.println("        </div>");
client.println("        <span class='date'></span>");
client.println("        <span class='vibor'>выбор устройвства: <span class='DB1 selectDB' style='text-decoration: underline black;'>dissterBOX</span>, <span class='DB2'  style='text-decoration: underline black;'>disasterBOX_mini</span></span>");
client.println("        <ul class='showing'>");
client.println("            <li><span class='tittle'>Осадки</span > <span class='pokasanie first' >");
client.println("<p id="switch_water_1">Loading...</p>");
client.println("</span></li>");
client.println("            <li><span class='tittle'>Температура</span> <span class='pokasanie second'>");
client.println("<p id="switch_DHTtem_1">Loading...</p>");
client.println("</span></li>");
client.println("<li><span class='tittle'>Крит. доза газов</span> <span class='pokasanie fourth'><p id="switch_MQ2_1">Loading...</p>");
client.println("</span></li>");
client.println("            <li><span class='tittle'>Влажность</span> <span class='pokasanie fifth'>");
client.println("<p id="switch_DHThum_1">Loading...</p>");
client.println("</span></li>");
client.println("            <li><span class='tittle'>Опасность землетрясения</span> <span class='pokasanie sixth'>");
client.println("<p id="switch_vibr_1">Loading...</p>");
client.println("</span></li>");
client.println("            <li><span class='tittle'>Огонь</span> <span class='pokasanie seventh' ><p id="switch_flame_1">Loading...");
client.println("</p></span></li>");
client.println("            <li><span class='tittle'>Давление</span> <span class='pokasanie third'>");
client.println("<p id="switch_prs_1">Loading...</p>");
client.println("</span></li>");
client.println("            <li><span class='tittle'>Освещение</span> <span class='pokasanie ninth'>");
client.println("<p id="switch_light">Loading...</p>");
client.println("</span></li>");
client.println("        </ul>");
client.println("        <button class='settings'>Настройка датчиков</button>");
client.println("    </div>");
client.println("    <div class='rightMain'>");
client.println("        <div class='showingimgs'>");
client.println("            <ul class='up'>");
client.println("                <li>");
client.println("                    <span class='titttle'><span>Темп. ,</span><span>влажн.</span></span>");
client.println("                    <div class='img'>");
client.println("                        <p>🌡️</p>");
client.println("                    </div>");
client.println("                    <div class='values'>");
client.println("                        <div class='value value_tem'><span>");
client.println("<p id="switch_DHTtem_2">Loading...</p>");
client.println("</span></div>");
client.println("                        <div class='value value_hum'><span>");
client.println("<p id="switch_DHThum_2">Loading...</p>");
client.println("</span></div>");
client.println("                    </div>");
client.println("                </li>");
client.println("                <li>");
client.println("                    <span class='titttle'>Осадки</span>");
client.println("                    <div class='img'>");
client.println("                        <p>🌧️</p>");
client.println("                    </div>");
client.println("                    <div class='values'>");
client.println("                        <div class='have have_rain'></div>");
client.println("                        <div class='value value_rain'>");
client.println("<p id="switch_water_2">Loading...</p>");
client.println("  <span>");
client.println("</span></div>");
client.println("                    </div>");
client.println("                </li>");
client.println("                <li>");
client.println("                    <span class='titttle'>Опасность землетрясения</span>");
client.println("                    <div class='img'>");
client.println("                        <p>♒</p>");
client.println("                    </div>");
client.println("                    <div class='values'>");
client.println("                        <div class='have have_wibro'></div>");
client.println("                        <div class='value value_wibro'><span>");
client.println("<p id="switch_vibr_2">Loading...</p>");
client.println("</span></div>");
client.println("                    </div>");
client.println("                </li>");
client.println("            </ul>");
client.println("            <ul class='bottom'>");
client.println("                <li>");
client.println("                    <span class='titttle'>Огонь</span>");
client.println("                    <div class='img'>");
client.println("                        <p>🔥</p>");
client.println("                    </div>");
client.println("                    <div class='values'>");
client.println("                        <div class='have have_flame'>");
client.println("</div>");
client.println("                        <div class='value value_flame'><span>");
client.println("<p id="switch_flame_2">Loading...</p>");
client.println("</span></div>");
client.println("                    </div>");
client.println("                </li>");
client.println("                <li>");
client.println("                    <span class='titttle'>Газ</span>");
client.println("                    <div class='img'>");
client.println("                        <p>💨</p>");
client.println("                    </div>");
client.println("                    <div class='values'>");
client.println("                <div class='have have_gass'>");
client.println("</div>");
client.println("                        <div class='value value_gass'><span>");
client.println("<p id="switch_MQ2_2">Loading...</p>");
client.println("</span></div>");
client.println("            </div>");
client.println("            </li>");
client.println("            <li>");
client.println("            <span class='titttle'>Давление</span>");
client.println("            <div class='img'>");
client.println("                <p>🧊</p>");
client.println("            </div>");
client.println("            <div class='values'>");
client.println("                <div class='have have_wind'></div>");
client.println("                <div class='value value_wind'><span>");
client.println("<p id="switch_prs_2">Loading...</p>");
client.println("</span></div>");
client.println("            </div>");
client.println("            </li>");
client.println("        </ul>");
client.println("        </div>");
client.println("        <script>");
client.println("            let date = document.querySelector('.date')");
client.println("            document.querySelector('.DB1').addEventListener('click',e=>{");
client.println("              document.querySelector('.DB1').classList.add('selectDB')");
client.println("              document.querySelector('.DB2').classList.remove('selectDB');addFlag1();");
client.println("            })");
client.println("            document.querySelector('.DB2').addEventListener('click',e=>{");
client.println("              document.querySelector('.DB2').classList.add('selectDB')");
client.println("              document.querySelector('.DB1').classList.remove('selectDB');addFlag2();");
client.println("            })");
client.println("            setInterval(() => {");
client.println("                date.innerHTML = `${(new Date).getDay()}.${(new Date).getMonth()}.${(new Date).getFullYear()} ${(new Date).getHours()}:${(new Date).getMinutes()}:${(new Date).getSeconds()}`");
client.println("            },1000)");
client.println("            let have_tem = document.querySelector('.value_tem')");
client.println("            let have_rain = document.querySelector('.have_rain')");
client.println("            let value_rain = document.querySelector('.value_rain')");
client.println("            let have_wibro = document.querySelector('.have_wibro')");
client.println("            let value_wibro = document.querySelector('.value_wibro')");
client.println("            let have_flame = document.querySelector('.have_flame')");
client.println("            let value_flame = document.querySelector('.value_flame')");
client.println("            let have_gas = document.querySelector('.have_gass')");
client.println("            let value_gas = document.querySelector('.value_gass')");
client.println("            let have_hum= document.querySelector('.value_hum')");
client.println("            let have_wind = document.querySelector('.have_wind')");
client.println("            let value_wind = document.querySelector('.value_wind')");
client.println("            let firstv = document.querySelector('.first')");
client.println("            let ninthv = document.querySelector('.ninth')");
client.println("            let eighteenthv = document.querySelector('.eighteenth')");
client.println("            let secondv = document.querySelector('.second')");
client.println("            let thirdv = document.querySelector('.third')");
client.println("            let fourthv = document.querySelector('.fourth')");
client.println("            let fifthv = document.querySelector('.fifth')");
client.println("            let sixthv = document.querySelector('.sixth')");
client.println("            let seventhv = document.querySelector('.seventh')");
client.println("if (+firstv.innerHTML.slice(0, firstv.innerHTML.length - 2) > 20){have_rain.style.background = 'var(--have)';have_rain.innerHTML = 'ОПАСНОСТЬ';}");
client.println("if (+secondv.innerHTML.slice(0, secondv.innerHTML.length - 4) > 2){have_wibro.style.background = 'var(--have)';have_wibro.innerHTML = 'ОПАСНОСТЬ';}");
client.println("if (+thirdv.innerText.slice(0, thirdv.innerText.length - 3) > 150 || +thirdv.innerText.slice(0, thirdv.innerText.length - 3) < 50){have_wind.style.background = 'var(--have)';have_wind.innerHTML = 'ОПАСНОСТЬ';}");
client.println("setInterval(() => {");
client.println("readSensorLight()");
client.println("readSensorFlame()");
client.println("readSensorMQ2()");
client.println("readSensorVibr()");
client.println("},100)");
client.println("setInterval(() => {");
client.println("readSensorWater()");
client.println("},500)");
client.println("setInterval(() => {");
client.println("readSensorDHTtem()");
client.println("readSensorDHThum()");
client.println("},1000)");
client.println("setInterval(() => {");
client.println("readSensorPrs()");
client.println("},5000)");
client.println("setInterval(() => {");
client.println("if (document.querySelector('.firstt').innerHTML == 'Выкл') {firstv.style.display = 'none'; firstv.parentNode.querySelector('.tittle').style.textDecoration = 'line-through';have_rain.style.display = 'none';value_rain.style.display = 'none'}");
client.println("else {firstv.style.display = 'inline'; firstv.parentNode.querySelector('.tittle').style.textDecoration = 'none'; have_rain.style.display = 'flex';value_rain.style.display = 'flex'}");
client.println("if (document.querySelector('.fourthh').innerHTML == 'Выкл') {fourthv.style.display = 'none'; fourthv.parentNode.querySelector('.tittle').style.textDecoration = 'line-through';have_gas.style.display = 'none';value_gas.style.display = 'none'}");
client.println("else {fourthv.style.display = 'inline'; fourthv.parentNode.querySelector('.tittle').style.textDecoration = 'none';have_gas.style.display = 'flex';value_gas.style.display = 'flex'}");
client.println("if (document.querySelector('.fifthh').innerHTML == 'Выкл') {fifthv.style.display = 'none'; fifthv.parentNode.querySelector('.tittle').style.textDecoration = 'line-through';have_hum.style.display = 'none'}");
client.println("else {fifthv.style.display = 'inline'; fifthv.parentNode.querySelector('.tittle').style.textDecoration = 'none';have_hum.style.display = 'flex'}");
client.println("if (document.querySelector('.secondd').innerHTML == 'Выкл') {secondv.style.display = 'none'; secondv.parentNode.querySelector('.tittle').style.textDecoration = 'line-through';have_tem.style.display = 'none'}");
client.println("else {secondv.style.display = 'inline'; secondv.parentNode.querySelector('.tittle').style.textDecoration = 'none';have_tem.style.display = 'flex'}");
client.println("if (document.querySelector('.sixthh').innerHTML == 'Выкл') {sixthv.style.display = 'none'; sixthv.parentNode.querySelector('.tittle').style.textDecoration = 'line-through';have_wibro.style.display = 'none';value_wibro.style.display = 'none'}");
client.println("else {sixthv.style.display = 'inline'; sixthv.parentNode.querySelector('.tittle').style.textDecoration = 'none';have_wibro.style.display = 'flex';value_wibro.style.display = 'flex'}");
client.println("if (document.querySelector('.eighteenthh').innerHTML == 'Выкл') {thirdv.style.display = 'none'; thirdv.parentNode.querySelector('.tittle').style.textDecoration = 'line-through';have_wind.style.display = 'none';value_wind.style.display = 'none'}");
client.println("else {thirdv.style.display = 'inline'; thirdv.parentNode.querySelector('.tittle').style.textDecoration = 'none';have_wind.style.display = 'flex';value_wind.style.display = 'flex'}");
client.println("if (document.querySelector('.ninthh').innerHTML == 'Выкл') {ninthv.style.display = 'none'; ninthv.parentNode.querySelector('.tittle').style.textDecoration = 'line-through'}");
client.println("else {ninthv.style.display = 'inline'; ninthv.parentNode.querySelector('.tittle').style.textDecoration = 'none'}");
client.println("if (document.querySelector('.seventhh').innerHTML == 'Выкл') {seventhv.style.display = 'none'; seventhv.parentNode.querySelector('.tittle').style.textDecoration = 'line-through';have_flame.style.display = 'none';value_flame.style.display = 'none'}");
client.println("else {seventhv.style.display = 'inline'; seventhv.parentNode.querySelector('.tittle').style.textDecoration = 'none';have_flame.style.display = 'flex';value_flame.style.display = 'flex'}");
client.println("},10)");
client.println("            let set = document.querySelector('.settings')");
client.println("            let menu = document.querySelector('.menu')");
client.println("            set.addEventListener('click', () => {");
client.println("                menu.style.display = 'block'");
client.println("                menu.querySelectorAll('.on').forEach(el => {");
client.println("                    el.addEventListener('click', () => {");
client.println("                        el.parentNode.querySelector('.pokasanie').innerHTML = 'Вкл'");
client.println("                    })");
client.println("                })");
client.println("                menu.querySelectorAll('.off').forEach(el => {");
client.println("                    el.addEventListener('click', () => {");
client.println("                        el.parentNode.querySelector('.pokasanie').innerHTML = 'Выкл'");
client.println("                    })");
client.println("                })");
client.println("                document.querySelector('.back').addEventListener('click', () => {");
client.println("                    menu.style.display = 'none'");
client.println("                })");
client.println("            })");
client.println("if (window.innerWidth == 768) {document.querySelector('.needfix').innerHTML = 'Температур. и влажность'}");
client.println("if (window.innerWidth <= 425) {");
client.println("document.querySelectorAll('.on').forEach(el => el.innerHTML = 'Вкл');");
client.println("document.querySelectorAll('.off').forEach(el => el.innerHTML = 'Выкл');");
client.println("document.querySelector('.needfix').innerHTML = 'Темп., влаж.';");
client.println("secondv.parentNode.querySelector('.tittle').innerHTML = 'Темп.';");
client.println("fifthv.parentNode.querySelector('.tittle').innerHTML = 'Влажн.';");
client.println("sixthv.parentNode.querySelector('.tittle').innerHTML = 'Землетрясения';");
client.println("}");
client.println("if (window.innerWidth <= 768) {document.querySelectorAll('.on').forEach(el => el.innerHTML = 'Вкл');");
client.println("document.querySelectorAll('.off').forEach(el => el.innerHTML = 'Выкл');}");
client.println("            if (window.innerWidth <= 425){");
client.println("                document.querySelectorAll('.on').forEach(el => el.innerHTML = 'Вкл')");
client.println("                document.querySelectorAll('.off').forEach(el => el.innerHTML = 'Выкл')");
client.println("                document.querySelector('.needfix').innerHTML = 'Темп., влаж.'");
client.println("                secondv.parentNode.querySelector('.tittle').innerHTML = 'Темп.'");
client.println("                fifthv.parentNode.querySelector('.tittle').innerHTML = 'Влажн.'");
client.println("                sixthv.parentNode.querySelector('.tittle').innerHTML = 'Толчки'");
client.println("            }");
client.println("            window.addEventListener('resize', () => {");
client.println("                if (window.innerWidth <= 425){");
client.println("                    document.querySelectorAll('.on').forEach(el => el.innerHTML = 'Вкл')");
client.println("                    document.querySelectorAll('.off').forEach(el => el.innerHTML = 'Выкл')");
client.println("                    document.querySelector('.needfix').innerHTML = 'Темп., влаж.'");
client.println("                    secondv.parentNode.querySelector('.tittle').innerHTML = 'Темп.'");
client.println("                    fifthv.parentNode.querySelector('.tittle').innerHTML = 'Влажн.'");
client.println("                    sixthv.parentNode.querySelector('.tittle').innerHTML = 'Толчки'");
client.println("                }");
client.println("if (window.innerWidth == 768) {document.querySelector('.needfix').innerHTML = 'Температур. и влажность'}");
client.println("if (window.innerWidth <= 768) {document.querySelectorAll('.on').forEach(el => el.innerHTML = 'Вкл');");
client.println("document.querySelectorAll('.off').forEach(el => el.innerHTML = 'Выкл');}");
client.println("            })");
client.println("        </script>");
client.println("    </body>");
client.println("</html>");
